.PHONY: clean
clean:
	make clean -C cat
	make clean -C class
	make clean -C function
	make clean -C lib-fsm
	make clean -C slice

.PHONY: test
test:
	make test -C cat
	make test -C class
	make test -C function
	make test -C lib-fsm
	make test -C slice
